# Generated by Django 3.0 on 2019-12-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightings',
            name='Age',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='Location',
            field=models.CharField(choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='Other_Activities',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='Primary_Fur_Color',
            field=models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'CInnamon'), ('Black', 'Black')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='Specific_Location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
