# Generated by Django 3.0 on 2019-12-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0002_auto_20191206_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightings',
            name='Date',
            field=models.CharField(help_text='Please use the following format: MMDDYYYY.', max_length=6),
        ),
    ]
