# Generated by Django 2.2.7 on 2019-12-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0004_auto_20191206_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightings',
            name='Date',
            field=models.CharField(help_text='Please use the following format: MMDDYYYY.', max_length=8),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='Latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='Longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='Shift',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=4),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='Unique_Squirrel_ID',
            field=models.CharField(max_length=100),
        ),
    ]
